/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipc.gui;
import minipc.hardware.CPU;
import minipc.hardware.Memoria;
import minipc.modelo.BCP;
import minipc.modelo.Instruccion;
import minipc.util.ParserASM;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author elenanito
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private CPU cpu;
    private Memoria memoria;
    private BCP bcp;
    private List<Instruccion> instruccionesActuales;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargar = new javax.swing.JButton();
        btnPaso_Paso = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInstrucciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMemoria = new javax.swing.JTable();
        lblTituloPC = new javax.swing.JLabel();
        lblValorPC = new javax.swing.JLabel();
        lblTituloIR = new javax.swing.JLabel();
        lblValorIR = new javax.swing.JLabel();
        lblTituloAC = new javax.swing.JLabel();
        lblValorAC = new javax.swing.JLabel();
        lblTituloAX = new javax.swing.JLabel();
        lblValorAX = new javax.swing.JLabel();
        lblTituloBX = new javax.swing.JLabel();
        lblValorBX = new javax.swing.JLabel();
        lblTituloCX = new javax.swing.JLabel();
        lblTituloDX = new javax.swing.JLabel();
        lblValorCX = new javax.swing.JLabel();
        lblValorDX = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTituloIdProceso = new javax.swing.JLabel();
        lblValorIdProceso = new javax.swing.JLabel();
        lblTituloEstado = new javax.swing.JLabel();
        lblValorEstado = new javax.swing.JLabel();
        lblTituloPCGuardado = new javax.swing.JLabel();
        lblValorPCGuardado = new javax.swing.JLabel();
        lblTituloACGuardado = new javax.swing.JLabel();
        lblValorACGuardado = new javax.swing.JLabel();
        lblTituloAXGuardado = new javax.swing.JLabel();
        lblValorAXGuardado = new javax.swing.JLabel();
        lblTituloBXGuardado = new javax.swing.JLabel();
        lblValorBXGuardado = new javax.swing.JLabel();
        lblTituloCXGuardado = new javax.swing.JLabel();
        lblValorCXGuardado = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblTituloDXGuardado = new javax.swing.JLabel();
        lblValorDXGuardado = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        txtTamanoTotal = new javax.swing.JTextField();
        txtTamanoSistema = new javax.swing.JTextField();
        btnAsignarMemoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargar.setText("Cargar archivo");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnPaso_Paso.setText("Paso a paso");
        btnPaso_Paso.addActionListener(this::btnPaso_PasoActionPerformed);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(this::btnEjecutarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tablaInstrucciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Binario", "Instrucciones"
            }
        ));
        jScrollPane1.setViewportView(tablaInstrucciones);

        tablaMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Posicion", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tablaMemoria);

        lblTituloPC.setText("PC:");

        lblValorPC.setText("0");

        lblTituloIR.setText("IR:");

        lblTituloAC.setText("AC:");

        lblValorAC.setText("0");

        lblTituloAX.setText("AX:");

        lblValorAX.setText("0");

        lblTituloBX.setText("BX:");

        lblValorBX.setText("0");

        lblTituloCX.setText("CX:");

        lblTituloDX.setText("DX:");

        lblValorCX.setText("0");

        lblValorDX.setText("0");

        jLabel15.setText("CPU");

        lblTituloIdProceso.setText("ID Proceso:");

        lblValorIdProceso.setText("-");

        lblTituloEstado.setText("Estado:");

        lblValorEstado.setText("-");

        lblTituloPCGuardado.setText("PC guardado:");

        lblValorPCGuardado.setText("-");

        lblTituloACGuardado.setText("AC guardado:");

        lblValorACGuardado.setText("-");

        lblTituloAXGuardado.setText("AX guardado:");

        lblValorAXGuardado.setText("-");

        lblTituloBXGuardado.setText("BX guardado:");

        lblValorBXGuardado.setText("-");

        lblTituloCXGuardado.setText("CX guardado:");

        lblValorCXGuardado.setText("-");

        jLabel30.setText("BCP");

        lblTituloDXGuardado.setText("DX guardado:");

        lblValorDXGuardado.setText("-");

        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);

        txtTamanoTotal.setText("128");
        txtTamanoTotal.addActionListener(this::txtTamanoTotalActionPerformed);

        txtTamanoSistema.setText("64");
        txtTamanoSistema.addActionListener(this::txtTamanoSistemaActionPerformed);

        btnAsignarMemoria.setText("Asignar memoria");
        btnAsignarMemoria.addActionListener(this::btnAsignarMemoriaActionPerformed);

        jLabel1.setText("Tamaño S.O.:");

        jLabel2.setText("Tamaño total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCargar)
                        .addGap(33, 33, 33)
                        .addComponent(btnPaso_Paso)
                        .addGap(35, 35, 35)
                        .addComponent(btnEjecutar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(31, 31, 31)
                        .addComponent(btnEstadisticas)
                        .addGap(45, 45, 45)
                        .addComponent(btnAsignarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloIR)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblValorIR, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloPC)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorPC))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblTituloBX)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblValorBX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblTituloAX)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblValorAX))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblTituloAC)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblValorAC)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloDX)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorDX)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloCX)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblValorCX)))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloCXGuardado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorCXGuardado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloBXGuardado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorBXGuardado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloAXGuardado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorAXGuardado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloACGuardado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorACGuardado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloPCGuardado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorPCGuardado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorEstado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloIdProceso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValorIdProceso))
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloDXGuardado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblValorDXGuardado)))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTamanoTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTamanoSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEjecutar)
                    .addComponent(btnPaso_Paso)
                    .addComponent(btnCargar)
                    .addComponent(btnEstadisticas)
                    .addComponent(btnAsignarMemoria))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTamanoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTamanoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel30))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloPC)
                            .addComponent(lblValorPC)
                            .addComponent(lblTituloIdProceso)
                            .addComponent(lblValorIdProceso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloIR)
                            .addComponent(lblTituloEstado)
                            .addComponent(lblValorEstado)
                            .addComponent(lblValorIR, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloAC)
                            .addComponent(lblValorAC)
                            .addComponent(lblTituloPCGuardado)
                            .addComponent(lblValorPCGuardado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloAX)
                            .addComponent(lblValorAX)
                            .addComponent(lblTituloACGuardado)
                            .addComponent(lblValorACGuardado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloBX)
                            .addComponent(lblValorBX)
                            .addComponent(lblTituloAXGuardado)
                            .addComponent(lblValorAXGuardado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloCX)
                            .addComponent(lblValorCX)
                            .addComponent(lblTituloBXGuardado)
                            .addComponent(lblValorBXGuardado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloDX)
                            .addComponent(lblValorDX)
                            .addComponent(lblTituloCXGuardado)
                            .addComponent(lblValorCXGuardado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloDXGuardado)
                            .addComponent(lblValorDXGuardado))))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarVista(){
        // Labels de CPU
        lblValorPC.setText("" + cpu.getPC());
        lblValorIR.setText(cpu.getIR());
        lblValorAC.setText("" + cpu.getAC());
        lblValorAX.setText("" + cpu.getAX());
        lblValorBX.setText("" + cpu.getBX());
        lblValorCX.setText("" + cpu.getCX());
        lblValorDX.setText("" + cpu.getDX());

        // Labels de BCP
        lblValorIdProceso.setText("" + bcp.getIdProceso());
        lblValorEstado.setText(bcp.getEstado());
        lblValorPCGuardado.setText("" + bcp.getPcGuardado());
        lblValorACGuardado.setText("" + bcp.getAcGuardado());
        lblValorAXGuardado.setText("" + bcp.getAxGuardado());
        lblValorBXGuardado.setText("" + bcp.getBxGuardado());
        lblValorCXGuardado.setText("" + bcp.getCxGuardado());
        lblValorDXGuardado.setText("" + bcp.getDxGuardado());
        actualizarTablaInstrucciones();
        actualizarTablaMemoria();
    }
    
    private void actualizarTablaInstrucciones(){
        String[] columnas = {"Instrucción", "Binario"};
        Object[][] datos = new Object[instruccionesActuales.size()][2];

        for(int i = 0; i < instruccionesActuales.size(); i++){
            Instruccion instr = instruccionesActuales.get(i);

            String textoInstruccion = instr.getoperacion() + " " + instr.getregistro();
            if(instr.getvalor() != null){
                textoInstruccion = textoInstruccion + ", " + instr.getvalor();
            }

            String textoBinario = instr.getcodigoBinarioOperacion();
            if(instr.getcodigoBinarioValor() != null){
                textoBinario = textoBinario + " " + instr.getcodigoBinarioValor();
            }

            datos[i][0] = textoInstruccion;
            datos[i][1] = textoBinario;
        }

        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
        tablaInstrucciones.setModel(modelo);
    }
    
    private void actualizarTablaMemoria(){
        String[] columnas = {"Posición", "Valor en memoria"};
        String[] todaLaMemoria = memoria.getTodasLasPosiciones();
        Object[][] datos = new Object[todaLaMemoria.length][2];

        // Mapa: posición -> texto de instrucción
        String[] textoEnPosicion = new String[todaLaMemoria.length];
        int posicionActual = memoria.getInicioUsuario();
        for(int i = 0; i < instruccionesActuales.size(); i++){
            Instruccion instr = instruccionesActuales.get(i);
            String textoInstruccion = instr.getoperacion() + " " + instr.getregistro();
            if(instr.getvalor() != null){
                textoInstruccion = textoInstruccion + ", " + instr.getvalor();
            }
            textoEnPosicion[posicionActual] = textoInstruccion;
            posicionActual = posicionActual + 1;
        }

        for(int i = 0; i < todaLaMemoria.length; i++){
            datos[i][0] = i;
            if(textoEnPosicion[i] != null){
                datos[i][1] = textoEnPosicion[i];
            } else {
                datos[i][1] = "";
            }
        }

        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
        tablaMemoria.setModel(modelo);
    }
    private void btnPaso_PasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaso_PasoActionPerformed
        if(cpu == null){
                JOptionPane.showMessageDialog(this, "Primero cargá un archivo", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if(cpu.programaTerminado()){
                JOptionPane.showMessageDialog(this, "El programa ya terminó de ejecutarse", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            cpu.pasoAPaso();
            actualizarVista();

    }//GEN-LAST:event_btnPaso_PasoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        if(cpu == null){
            JOptionPane.showMessageDialog(this, "No hay nada cargado para limpiar", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        cpu = null;
        memoria = null;
        bcp = null;
        instruccionesActuales = null;

        lblValorPC.setText("0");
        lblValorIR.setText("");
        lblValorAC.setText("0");
        lblValorAX.setText("0");
        lblValorBX.setText("0");
        lblValorCX.setText("0");
        lblValorDX.setText("0");

        lblValorIdProceso.setText("-");
        lblValorEstado.setText("-");
        lblValorPCGuardado.setText("-");
        lblValorACGuardado.setText("-");
        lblValorAXGuardado.setText("-");
        lblValorBXGuardado.setText("-");
        lblValorCXGuardado.setText("-");
        lblValorDXGuardado.setText("-");

        DefaultTableModel modeloVacioInstrucciones = new DefaultTableModel(new Object[0][2], new String[]{"Instrucción", "Binario"});
        tablaInstrucciones.setModel(modeloVacioInstrucciones);

        DefaultTableModel modeloVacioMemoria = new DefaultTableModel(new Object[0][2], new String[]{"Posición", "Valor en memoria"});
        tablaMemoria.setModel(modeloVacioMemoria);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);

        if(resultado == JFileChooser.APPROVE_OPTION){
            File archivoSeleccionado = selector.getSelectedFile();

            if(!archivoSeleccionado.getName().endsWith(".asm")){
                JOptionPane.showMessageDialog(this, "El archivo debe tener extensión .asm", "Archivo inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                instruccionesActuales = ParserASM.leerArchivo(archivoSeleccionado);

                memoria = new Memoria(128, 64);
                cpu = new CPU(memoria);
                cpu.cargarPrograma(instruccionesActuales);

                bcp = new BCP(1, "Nuevo");
                bcp.capturaEstado(cpu);

                actualizarVista();

            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error en el archivo", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "No se pudo leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "El archivo no tiene un formato de texto válido. Asegúrate de que sea un archivo .asm de texto plano.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void txtTamanoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanoTotalActionPerformed

    private void btnAsignarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMemoriaActionPerformed
        if(cpu != null && !cpu.programaTerminado()){
            JOptionPane.showMessageDialog(this, "No se puede asignar memoria mientras un programa está en ejecución. Terminá la ejecución o dale a Limpiar primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String textoTotal = txtTamanoTotal.getText().trim();
        String textoSistema = txtTamanoSistema.getText().trim();

        int tamanoTotal;
        int tamanoSistema;

        try {
            tamanoTotal = Integer.parseInt(textoTotal);
            tamanoSistema = Integer.parseInt(textoSistema);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los tamaños deben ser números enteros", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(tamanoTotal < 256){
            JOptionPane.showMessageDialog(this, "El tamaño total debe ser de al menos 256", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(tamanoSistema < 64 || tamanoSistema >= tamanoTotal){
            JOptionPane.showMessageDialog(this, "El tamaño del S.O. debe ser de al menos 64 y menor al tamaño total", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        memoria = new Memoria(tamanoTotal, tamanoSistema);
        cpu = new CPU(memoria);
        instruccionesActuales = null;
        bcp = null;

        JOptionPane.showMessageDialog(this, "Memoria asignada: " + tamanoTotal + " posiciones, " + tamanoSistema + " para el S.O.", "Memoria asignada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAsignarMemoriaActionPerformed

    private void txtTamanoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanoSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanoSistemaActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
    if(cpu == null){
        JOptionPane.showMessageDialog(this, "Primero cargá un archivo", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if(cpu.programaTerminado()){
        JOptionPane.showMessageDialog(this, "El programa ya terminó de ejecutarse", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    cpu.ejecutarTodo();
    actualizarVista();
    }//GEN-LAST:event_btnEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarMemoria;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPaso_Paso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTituloAC;
    private javax.swing.JLabel lblTituloACGuardado;
    private javax.swing.JLabel lblTituloAX;
    private javax.swing.JLabel lblTituloAXGuardado;
    private javax.swing.JLabel lblTituloBX;
    private javax.swing.JLabel lblTituloBXGuardado;
    private javax.swing.JLabel lblTituloCX;
    private javax.swing.JLabel lblTituloCXGuardado;
    private javax.swing.JLabel lblTituloDX;
    private javax.swing.JLabel lblTituloDXGuardado;
    private javax.swing.JLabel lblTituloEstado;
    private javax.swing.JLabel lblTituloIR;
    private javax.swing.JLabel lblTituloIdProceso;
    private javax.swing.JLabel lblTituloPC;
    private javax.swing.JLabel lblTituloPCGuardado;
    private javax.swing.JLabel lblValorAC;
    private javax.swing.JLabel lblValorACGuardado;
    private javax.swing.JLabel lblValorAX;
    private javax.swing.JLabel lblValorAXGuardado;
    private javax.swing.JLabel lblValorBX;
    private javax.swing.JLabel lblValorBXGuardado;
    private javax.swing.JLabel lblValorCX;
    private javax.swing.JLabel lblValorCXGuardado;
    private javax.swing.JLabel lblValorDX;
    private javax.swing.JLabel lblValorDXGuardado;
    private javax.swing.JLabel lblValorEstado;
    private javax.swing.JLabel lblValorIR;
    private javax.swing.JLabel lblValorIdProceso;
    private javax.swing.JLabel lblValorPC;
    private javax.swing.JLabel lblValorPCGuardado;
    private javax.swing.JTable tablaInstrucciones;
    private javax.swing.JTable tablaMemoria;
    private javax.swing.JTextField txtTamanoSistema;
    private javax.swing.JTextField txtTamanoTotal;
    // End of variables declaration//GEN-END:variables
}
