/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipc.gui;
import minipc.hardware.CPU;
import minipc.hardware.Memoria;
import minipc.modelo.BCP;
import minipc.modelo.Instruccion;
import minipc.util.ParserASM;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author elenanito
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private CPU cpu;
    private Memoria memoria;
    private BCP bcp;
    private List<Instruccion> instruccionesActuales;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargar = new javax.swing.JButton();
        btnPaso_Paso = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInstrucciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMemoria = new javax.swing.JTable();
        lblTituloPC = new javax.swing.JLabel();
        lblValorPC = new javax.swing.JLabel();
        lblTituloIR = new javax.swing.JLabel();
        lblValorIR = new javax.swing.JLabel();
        lblTituloAC = new javax.swing.JLabel();
        lblValorAC = new javax.swing.JLabel();
        lblTituloAX = new javax.swing.JLabel();
        lblValorAX = new javax.swing.JLabel();
        lblTituloBX = new javax.swing.JLabel();
        lblValorBX = new javax.swing.JLabel();
        lblTituloCX = new javax.swing.JLabel();
        lblTituloDX = new javax.swing.JLabel();
        lblValorCX = new javax.swing.JLabel();
        lblValorDX = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnEstadisticas = new javax.swing.JButton();
        txtTamanoTotal = new javax.swing.JTextField();
        txtTamanoSistema = new javax.swing.JTextField();
        btnAsignarMemoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargar.setText("Cargar archivo");
        btnCargar.addActionListener(this::btnCargarActionPerformed);

        btnPaso_Paso.setText("Paso a paso");
        btnPaso_Paso.addActionListener(this::btnPaso_PasoActionPerformed);

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(this::btnEjecutarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        tablaInstrucciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Binario", "Instrucciones"
            }
        ));
        jScrollPane1.setViewportView(tablaInstrucciones);

        tablaMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Posicion", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tablaMemoria);

        lblTituloPC.setText("PC:");

        lblValorPC.setText("0");

        lblTituloIR.setText("IR:");

        lblTituloAC.setText("AC:");

        lblValorAC.setText("0");

        lblTituloAX.setText("AX:");

        lblValorAX.setText("0");

        lblTituloBX.setText("BX:");

        lblValorBX.setText("0");

        lblTituloCX.setText("CX:");

        lblTituloDX.setText("DX:");

        lblValorCX.setText("0");

        lblValorDX.setText("0");

        jLabel15.setText("BCP actual CPU");

        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);

        txtTamanoTotal.setText("256");
        txtTamanoTotal.addActionListener(this::txtTamanoTotalActionPerformed);

        txtTamanoSistema.setText("64");
        txtTamanoSistema.addActionListener(this::txtTamanoSistemaActionPerformed);

        btnAsignarMemoria.setText("Asignar memoria");
        btnAsignarMemoria.addActionListener(this::btnAsignarMemoriaActionPerformed);

        jLabel1.setText("Tamaño S.O.:");

        jLabel2.setText("Tamaño total:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(55, 55, 55)
                        .addComponent(btnCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaso_Paso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstadisticas)
                        .addGap(30, 30, 30)
                        .addComponent(btnAsignarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloPC)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorPC))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloBX)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorBX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloAX)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorAX))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloAC)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorAC))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTituloDX)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorDX)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloCX)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblValorCX))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloIR)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblValorIR, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTamanoTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTamanoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(14, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEjecutar)
                    .addComponent(btnPaso_Paso)
                    .addComponent(btnCargar)
                    .addComponent(btnEstadisticas)
                    .addComponent(btnAsignarMemoria)
                    .addComponent(btnSalir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTamanoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtTamanoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel15)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloPC)
                            .addComponent(lblValorPC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorIR, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloIR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloAC)
                            .addComponent(lblValorAC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloAX)
                            .addComponent(lblValorAX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloBX)
                            .addComponent(lblValorBX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloCX)
                            .addComponent(lblValorCX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloDX)
                            .addComponent(lblValorDX))))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarVista(){
        lblValorPC.setText("" + cpu.getPC());
        lblValorIR.setText(cpu.getIR());
        lblValorAC.setText("" + cpu.getAC());
        lblValorAX.setText("" + cpu.getAX());
        lblValorBX.setText("" + cpu.getBX());
        lblValorCX.setText("" + cpu.getCX());
        lblValorDX.setText("" + cpu.getDX());

        actualizarTablaInstrucciones();
        actualizarTablaMemoria();
    }
    
    private void actualizarTablaInstrucciones(){
        String[] columnas = {"Instrucción", "Binario"};
        Object[][] datos = new Object[instruccionesActuales.size()][2];

        for(int i = 0; i < instruccionesActuales.size(); i++){
            Instruccion instr = instruccionesActuales.get(i);

            String textoInstruccion = instr.getoperacion() + " " + instr.getregistro();
            if(instr.getvalor() != null){
                textoInstruccion = textoInstruccion + ", " + instr.getvalor();
            }

            String textoBinario = instr.getcodigoBinarioOperacion();
            if(instr.getcodigoBinarioValor() != null){
                textoBinario = textoBinario + " " + instr.getcodigoBinarioValor();
            }

            datos[i][0] = textoInstruccion;
            datos[i][1] = textoBinario;
        }

        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
        tablaInstrucciones.setModel(modelo);
    }
    
    private void actualizarTablaMemoria(){
        String[] columnas = {"Posición", "Valor en memoria"};
        String[] todaLaMemoria = memoria.getTodasLasPosiciones();
        Object[][] datos = new Object[todaLaMemoria.length][2];

        // Mapa: posición -> texto de instrucción
        String[] textoEnPosicion = new String[todaLaMemoria.length];
        int posicionActual = memoria.getInicioUsuario();
        for(int i = 0; i < instruccionesActuales.size(); i++){
            Instruccion instr = instruccionesActuales.get(i);
            String textoInstruccion = instr.getoperacion() + " " + instr.getregistro();
            if(instr.getvalor() != null){
                textoInstruccion = textoInstruccion + ", " + instr.getvalor();
            }
            textoEnPosicion[posicionActual] = textoInstruccion;
            posicionActual = posicionActual + 1;
        }

        for(int i = 0; i < todaLaMemoria.length; i++){
            datos[i][0] = i;
            if(textoEnPosicion[i] != null){
                datos[i][1] = textoEnPosicion[i];
            } else {
                datos[i][1] = "";
            }
        }

        DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
        tablaMemoria.setModel(modelo);
    }
    private void btnPaso_PasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaso_PasoActionPerformed
        if(cpu == null){
                JOptionPane.showMessageDialog(this, "Primero cargá un archivo", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if(cpu.programaTerminado()){
                JOptionPane.showMessageDialog(this, "El programa ya terminó de ejecutarse", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            cpu.pasoAPaso();
            actualizarVista();

    }//GEN-LAST:event_btnPaso_PasoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        if(cpu == null){
            JOptionPane.showMessageDialog(this, "No hay nada cargado para limpiar", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!cpu.programaTerminado()){
            int confirmacion = JOptionPane.showConfirmDialog(this, "El programa todavía no terminó de ejecutarse.\n ¿Querés limpiarlo de todas formas?", "Confirmar limpieza", JOptionPane.YES_NO_OPTION);
            if(confirmacion != JOptionPane.YES_OPTION){
                return;
            }
        }

        cpu = null;
        memoria = null;
        bcp = null;
        instruccionesActuales = null;

        lblValorPC.setText("0");
        lblValorIR.setText("");
        lblValorAC.setText("0");
        lblValorAX.setText("0");
        lblValorBX.setText("0");
        lblValorCX.setText("0");
        lblValorDX.setText("0");

        DefaultTableModel modeloVacioInstrucciones = new DefaultTableModel(new Object[0][2], new String[]{"Instrucción", "Binario"});
        tablaInstrucciones.setModel(modeloVacioInstrucciones);

        DefaultTableModel modeloVacioMemoria = new DefaultTableModel(new Object[0][2], new String[]{"Posición", "Valor en memoria"});
        tablaMemoria.setModel(modeloVacioMemoria);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        if(cpu == null){
            JOptionPane.showMessageDialog(this, "Primero cargá un archivo", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int instruccionesEjecutadas = cpu.getPC() - memoria.getInicioUsuario();

        int contadorLoad = 0;
        int contadorStore = 0;
        int contadorMov = 0;
        int contadorAdd = 0;
        int contadorSub = 0;

        for(int i = 0; i < instruccionesEjecutadas; i++){
            String operacion = instruccionesActuales.get(i).getoperacion();

            if(operacion.equals("LOAD")){
                contadorLoad = contadorLoad + 1;
            }else if(operacion.equals("STORE")){
                contadorStore = contadorStore + 1;
            }else if(operacion.equals("MOV")){
                contadorMov = contadorMov + 1;
            }else if(operacion.equals("ADD")){
                contadorAdd = contadorAdd + 1;
            }else if(operacion.equals("SUB")){
                contadorSub = contadorSub + 1;
            }
        }

        String mensaje = "=== PROGRESO DE EJECUCIÓN ===\n";
        mensaje = mensaje + "Instrucciones ejecutadas: " + instruccionesEjecutadas + " de " + instruccionesActuales.size() + "\n";
        mensaje = mensaje + "PC actual: " + cpu.getPC() + "\n";
        mensaje = mensaje + "\n";
        mensaje = mensaje + "=== OPERACIONES UTILIZADAS ===\n";

        if(instruccionesEjecutadas == 0){
            mensaje = mensaje + "(todavía no se ejecutó ninguna instrucción)";
        } else {
            if(contadorLoad > 0){ mensaje = mensaje + "LOAD (0001): " + contadorLoad + "\n"; }
            if(contadorStore > 0){ mensaje = mensaje + "STORE (0010): " + contadorStore + "\n"; }
            if(contadorMov > 0){ mensaje = mensaje + "MOV (0011): " + contadorMov + "\n"; }
            if(contadorSub > 0){ mensaje = mensaje + "SUB (00100): " + contadorSub + "\n"; }
            if(contadorAdd > 0){ mensaje = mensaje + "ADD (0101): " + contadorAdd + "\n"; }
        }

        JOptionPane.showMessageDialog(this, mensaje, "Estadísticas de ejecución", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);

        if(resultado == JFileChooser.APPROVE_OPTION){
            File archivoSeleccionado = selector.getSelectedFile();

            if(!archivoSeleccionado.getName().endsWith(".asm")){
                JOptionPane.showMessageDialog(this, "El archivo debe tener extensión .asm", "Archivo inválido", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                instruccionesActuales = ParserASM.leerArchivo(archivoSeleccionado);

                if(memoria == null){
                    memoria = new Memoria(256, 64);
                }
                cpu = new CPU(memoria);
                cpu.cargarPrograma(instruccionesActuales);

                bcp = new BCP(1, "Nuevo");
                bcp.capturaEstado(cpu);

                actualizarVista();

            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error en el archivo", JOptionPane.ERROR_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "No se pudo leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "El archivo no tiene un formato de texto válido. Asegúrate de que sea un archivo .asm de texto plano.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void txtTamanoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanoTotalActionPerformed

    private void btnAsignarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarMemoriaActionPerformed
        if(cpu != null && !cpu.programaTerminado()){
            JOptionPane.showMessageDialog(this, "No se puede asignar memoria mientras un programa está en ejecución. Terminá la ejecución o dale a Limpiar primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String textoTotal = txtTamanoTotal.getText().trim();
        String textoSistema = txtTamanoSistema.getText().trim();

        int tamanoTotal;
        int tamanoSistema;

        try {
            tamanoTotal = Integer.parseInt(textoTotal);
            tamanoSistema = Integer.parseInt(textoSistema);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los tamaños deben ser números enteros", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(tamanoTotal < 256){
            JOptionPane.showMessageDialog(this, "El tamaño total debe ser de al menos 256", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(tamanoSistema < 64 || tamanoSistema >= tamanoTotal){
            JOptionPane.showMessageDialog(this, "El tamaño del S.O. debe ser de al menos 64 y menor al tamaño total", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        cpu = null;
        memoria = null;
        bcp = null;
        instruccionesActuales = null;

        lblValorPC.setText("0");
        lblValorIR.setText("");
        lblValorAC.setText("0");
        lblValorAX.setText("0");
        lblValorBX.setText("0");
        lblValorCX.setText("0");
        lblValorDX.setText("0");

        DefaultTableModel modeloVacioInstrucciones = new DefaultTableModel(new Object[0][2], new String[]{"Instrucción", "Binario"});
        tablaInstrucciones.setModel(modeloVacioInstrucciones);

        DefaultTableModel modeloVacioMemoria = new DefaultTableModel(new Object[0][2], new String[]{"Posición", "Valor en memoria"});
        tablaMemoria.setModel(modeloVacioMemoria);
        
        memoria = new Memoria(tamanoTotal, tamanoSistema);
        cpu = new CPU(memoria);
        instruccionesActuales = null;
        bcp = null;
        
                



        JOptionPane.showMessageDialog(this, "Memoria asignada: " + tamanoTotal + " posiciones, " + tamanoSistema + " para el S.O.", "Memoria asignada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAsignarMemoriaActionPerformed

    private void txtTamanoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanoSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanoSistemaActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
    if(cpu == null){
        JOptionPane.showMessageDialog(this, "Primero cargá un archivo", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if(cpu.programaTerminado()){
        JOptionPane.showMessageDialog(this, "El programa ya terminó de ejecutarse", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    cpu.ejecutarTodo();
    actualizarVista();
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Seguro que querés salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if(confirmacion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarMemoria;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPaso_Paso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTituloAC;
    private javax.swing.JLabel lblTituloAX;
    private javax.swing.JLabel lblTituloBX;
    private javax.swing.JLabel lblTituloCX;
    private javax.swing.JLabel lblTituloDX;
    private javax.swing.JLabel lblTituloIR;
    private javax.swing.JLabel lblTituloPC;
    private javax.swing.JLabel lblValorAC;
    private javax.swing.JLabel lblValorAX;
    private javax.swing.JLabel lblValorBX;
    private javax.swing.JLabel lblValorCX;
    private javax.swing.JLabel lblValorDX;
    private javax.swing.JLabel lblValorIR;
    private javax.swing.JLabel lblValorPC;
    private javax.swing.JTable tablaInstrucciones;
    private javax.swing.JTable tablaMemoria;
    private javax.swing.JTextField txtTamanoSistema;
    private javax.swing.JTextField txtTamanoTotal;
    // End of variables declaration//GEN-END:variables
}
